---
title: "Data Processing"
author: "Syeda Aleya"
date: "27/09/2022"
output: html_document
---

```{r}

### Using 40 Attributes
census22_initial <- read.csv("C:/Users/sania/Data analytics/Course materials 820/Latest census/Data collection/census22_initial.csv")


```

```{r}
str(census22)

```


```{r}
### Subset of Age=0[Not in Universe]

df1<-subset(census22_initial, PTOTVAL =="0")

```


```{r}


### Removing NiU

Census22_40row<-subset(census22_initial, PTOTVAL >"0")
head(Census22_40row)

```




```{r}
# Creating Quartiles of income

#install.packages("gtools")
library(gtools)

```

```{r}
### 2 levels of income from quartiles

Census_2q <- Census22_40row

QR<- quantcut(Census_2q$PTOTVAL, q=2, na.rm = TRUE)
table(QR)
Income_levels <- c("Low","High")
Census_2q$Income  <- factor(QR, labels=Income_levels)
Census22_2QT <- subset(Census_2q, select = -c(PTOTVAL))

```

```{r}

Census_2qn <- Census22_40row

qr<- quantcut(Census_2qn$PTOTVAL, q=2, na.rm = TRUE)
table(QR)
Income_levels <- c(1,2)
Census_2qn$Income  <- factor(QR, labels=Income_levels)
Census22_2qn <- subset(Census_2qn, select = -c(PTOTVAL))
```


```{r}

### 3 levels of income from quartiles

Census_3q <- Census22_40row

QR<- quantcut(Census_3q$PTOTVAL, q=3, na.rm = TRUE)
table(QR)
Income_levels <- c("Low","Medium","High")
Census_3q$Income  <- factor(QR, labels=Income_levels)
Census22_3QT <- subset(Census_3q, select = -c(PTOTVAL))
```

```{r}

### 5 levels of income from quartiles

Census_5q <- Census22_40row

QR<- quantcut(Census22_40row$PTOTVAL, q=5, na.rm = TRUE)
table(QR)
Income_levels <- c("Low","LowerMedium", "Medium","LowerHigh","High")


Census_5q$Income  <- factor(QR, labels=Income_levels)
Census22_5QT <- subset(Census_5q, select = -c(PTOTVAL))


```

```{r}
### 10 levels of income from quartiles

Census_10q <- Census22_40row

QR<- quantcut(Census22_40row$PTOTVAL, q=10, na.rm = TRUE)
table(QR)
Income_levels <- c(1,2,3,4,5,6,7,8,9,10)


Census_10q$Income  <- factor(QR, labels=Income_levels)
Census22_10QT <- subset(Census_10q, select = -c(PTOTVAL))

```

```{r}

write.csv(Census22_2QT, "C:/Users/sania/Data analytics/Course materials 820/Latest census/Initial Data analysis/Preparing Target Variable/Census22_2QT.csv")
write.csv(Census22_3QT, "C:/Users/sania/Data analytics/Course materials 820/Latest census/Initial Data analysis/Preparing Target Variable/Census22_3QT.csv")
write.csv(Census22_5QT, "C:/Users/sania/Data analytics/Course materials 820/Latest census/Initial Data analysis/Preparing Target Variable/Census22_5QT.csv")
write.csv(Census22_10QT, "C:/Users/sania/Data analytics/Course materials 820/Latest census/Initial Data analysis/Preparing Target Variable/Census22_10QT.csv")
```

```{r}

write.csv(Census22_2qn, "C:/Users/sania/Data analytics/Course materials 820/Latest census/Initial Data analysis/Preparing Target Variable/Census22_2qn.csv")
```


```{r}



```




```{r}

### Forward selection
#install.packages("nnet")
library(nnet)

#define intercept-only model
intercept_only <- multinom(Income ~ 1, data=Census22_2QT)

#define model with all predictors
all <- multinom(Income ~ ., data=Census22_2QT)

#perform forward stepwise regression
forward <- step(intercept_only, direction='forward', scope=formula(all), trace=0)

#view results of forward stepwise regression
forward$anova

#view final model
forward$coefficients
```

```{r}

summary(forward)

```


```{r}
### Backward elimination

all <- multinom(Income ~ ., data=Census22)
backward <- step(all, direction = "backward", trace=FALSE ) 

#view results of backward stepwise regression
backward$anova

#view final model
backward$coefficients
```


```{r}

summary(backward)
```


```{r}
### Both

all <- multinom(Income ~ ., data=Census22)
both <- step(intercept_only, direction='both', scope=formula(all), trace=0)

#view results of forward stepwise regression
both$anova

#view final model
both$coefficients

```


````{r}
summary(both)

```

```{r}
table(Census22$Income)

```


```{r}



```

