---
title: "Untitled"
author: "Syeda Aleya"
date: "04/10/2022"
output: html_document
---

```{r}

Census22_40 <- read.csv("C:/Users/sania/Data analytics/Course materials 820/Latest census/Initial Data analysis/Correlation Cofficients/Census22_40.csv")
```

```{r}
numeric_attributes <- subset(Census22_40, select = c("Income", "A_AGE","A_HRSPAY","CAP_VAL","DIV_VAL","STATETAX_A","STATETAX_B","WKSWORK"))
write.csv(numeric_attributes, "C:/Users/sania/Data analytics/Course materials 820/Latest census/Initial Data analysis/Correlation Cofficients/Numeric_Attributes.csv")


nominal_attributes <- subset(Census22_40, select = -c(A_AGE, A_HRSPAY, CAP_VAL, DIV_VAL, STATETAX_A, STATETAX_B, WKSWORK))
write.csv(nominal_attributes, "C:/Users/sania/Data analytics/Course materials 820/Latest census/Initial Data analysis/Correlation Cofficients/Nominal_Attributes.csv")

```


```{r}
### Remove attributes with an absolute correlation of 0.75 or higher.

# To ensure the results are repeatable
set.seed(7)
# load the library
#install.packages("mlbench")
library(mlbench)
library(caret)

# calculate correlation matrix
correlationMatrix <- cor(Census22_40)
# summarize the correlation matrix
print(correlationMatrix)
# find attributes that are highly corrected (ideally >0.75)
highlyCorrelated <- findCorrelation(correlationMatrix, cutoff=0.5)
# print indexes of highly correlated attributes
print(highlyCorrelated)

```

```{r}
# calculate correlation matrix
correlationMatrix <- cor(nominal_attributes)
# summarize the correlation matrix
print(correlationMatrix)
# find attributes that are highly corrected (ideally >0.75)
highlyCorrelated <- findCorrelation(correlationMatrix, cutoff=0.5)
# print indexes of highly correlated attributes
print(highlyCorrelated)

```


```{r}

# calculate correlation matrix
correlationMatrix <- cor(numeric_attributes)
# summarize the correlation matrix
print(correlationMatrix)
# find attributes that are highly corrected (ideally >0.75)
highlyCorrelated <- findCorrelation(correlationMatrix, cutoff=0.5)
# print indexes of highly correlated attributes
print(highlyCorrelated)
```

```{r}

high_cor<- Census22_40[1,c(34, 10, 20, 17, 16, 23, 14,  6,  7,  5, 24,  3,  2, 36, 19, 33)]

```

```{r}

not_high_cor <- Census22_40[-c(34, 10, 20, 17, 16, 23, 14,  6,  7,  5, 24,  3,  2, 36, 19, 33)]
```


```{r}

write.csv(not_high_cor, "C:/Users/sania/Data analytics/Course materials 820/Latest census/Initial Data analysis/Correlation Cofficients/Not_high_corr.csv")

```